server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    globally_quoted_identifiers: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
    username: postgres
    password: 12345


